### ISSUE TITLE
*multiple* - Cannot read properties of undefined (reading '_focus')

### ISSUE THREAD

**Issue by M1z23R** [anubra266/choc-autocomplete#177]
Hi, I am having trouble when applying the "multiple" prop.

`Unexpected Application Error!
Cannot read properties of undefined (reading '_focus')
TypeError: Cannot read properties of undefined (reading '_focus')
    at getMultipleWrapStyles2 (http://localhost:5174/node_modules/.vite/deps/@choc-ui_chakra-autocomplete.js?v=b97dfcbf:39604:40)
    at getInputProps2 (http://localhost:5174/node_modules/.vite/deps/@choc-ui_chakra-autocomplete.js?v=b97dfcbf:39803:14)
    at http://localhost:5174/node_modules/.vite/deps/@choc-ui_chakra-autocomplete.js?v=b97dfcbf:40143:28
    at renderWithHooks (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:12171:26)
    at updateForwardRef (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:14327:28)
    at beginWork (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:15934:22)
    at beginWork$1 (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:19749:22)
    at performUnitOfWork (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:19194:20)
    at workLoopSync (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:19133:13)
    at renderRootSync (http://localhost:5174/node_modules/.vite/deps/chunk-QJV3R4PZ.js?v=b97dfcbf:19112:15)`

**Comment by Kysluss** [comment]
@M1z23R I did some testing and this seems to be the case if you don't wrap your App component with ChakraProvider

index.js that produces error

```
createRoot(document.getElementById("root")).render(
  <React.StrictMode>
      <App />
  </React.StrictMode>
)
```

index.js that does not produce error

```
createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <ChakraProvider>
      <App />
    </ChakraProvider>
  </React.StrictMode>
)
```

App component was same for both (taken from README.md)

```
import { Flex, FormControl, FormHelperText, FormLabel } from "@chakra-ui/react";
import * as React from "react";
import {
  AutoComplete,
  AutoCompleteInput,
  AutoCompleteItem,
  AutoCompleteList,
  AutoCompleteTag,
} from "./choc-autocomplete";

function App() {
  const countries = [
    "nigeria",
    "japan",
    "india",
    "united states",
    "south korea",
  ];

  return (
    <Flex pt="48" justify="center" align="center" w="full" direction="column">
      <FormControl id="email" w="60">
        <FormLabel>Olympics Soccer Winner</FormLabel>
        <AutoComplete openOnFocus multiple onChange={vals => console.log(vals)}>
          <AutoCompleteInput variant="filled">
            {({ tags }) =>
              tags.map((tag, tid) => (
                <AutoCompleteTag
                  key={tid}
                  label={tag.label}
                  onRemove={tag.onRemove}
                />
              ))
            }
          </AutoCompleteInput>
          <AutoCompleteList>
            {countries.map((country, cid) => (
              <AutoCompleteItem
                key={`option-${cid}`}
                value={country}
                textTransform="capitalize"
                _selected={{ bg: "whiteAlpha.50" }}
                _focus={{ bg: "whiteAlpha.100" }}
              >
                {country}
              </AutoCompleteItem>
            ))}
          </AutoCompleteList>
        </AutoComplete>
        <FormHelperText>Who do you support.</FormHelperText>
      </FormControl>
    </Flex>
  );
}

export default App;
```

**Comment by sakanaproductions** [comment]
I am running into the same issue, I have confirmed that I have `ChakraProvider` wrapped around the component.  It is happening with `multiple` selected, and seems to be happening within the `AutoComplete` tag.  Here's the complete error:
```
hook.js:608 TypeError: Cannot read properties of undefined (reading '_focus')
    at F (index.es.js:814:29)
    at getInputProps (index.es.js:994:14)
    at index.es.js:1277:36
    at uo (react-dom.production.min.js:157:137)
    at Vo (react-dom.production.min.js:176:260)
    at Xu (react-dom.production.min.js:271:400)
    at Oi (react-dom.production.min.js:250:347)
    at zi (react-dom.production.min.js:250:278)
    at Ti (react-dom.production.min.js:250:138)
    at ki (react-dom.production.min.js:243:163)
 ```
    
Here is the `AutoComplete`:
```
    <Controller
      control={control}
      name="equipment"
      render={({ field }) => (
        <AutoComplete
          openOnFocus
          multiple
          restoreOnBlurIfEmpty={false}
          onChange={(vals) => {
            field.onChange(vals);
            setValue("slots", vals.length);
          }}
          value={field?.value}
          disabled={watch("slots") > 0 || equipment?.data?.length === 0}
        >
          {({ isOpen }) => (
            <>
              <InputGroup>
                <AutoCompleteInput>
                  {({ tags }) =>
                    tags?.map((tag, tid) => (
                      <AutoCompleteTag
                        key={tid}
                        label={
                          equipment?.data?.find(
                            (e) => e.id === tag.label
                          )?.name
                        }
                        onRemove={tag.onRemove}
                      />
                    ))
                  }
                </AutoCompleteInput>
                <InputRightElement>
                  <Icon as={isOpen ? ChevronUpIcon : ChevronDownIcon} />
                </InputRightElement>
              </InputGroup>
              <AutoCompleteList>
                {equipment?.data?.map(({ name, id }) => (
                  <AutoCompleteItem
                    key={`equipment-${id}`}
                    value={id}
                    textTransform="capitalize"
                    _selected={{ bg: "whiteAlpha.50" }}
                    _focus={{ bg: "whiteAlpha.100" }}
                  >
                    {name}
                  </AutoCompleteItem>
                ))}
              </AutoCompleteList>
            </>
          )}
        </AutoComplete>
      )}
    />
````
